# Generated by Django 6.0.3 on 2026-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='temp@example.com', max_length=254, verbose_name='Email для чека'),
            preserve_default=False,
        ),
    ]
